# fly.toml app configuration file generated for docker-nginx-rani on 2024-02-13T16:24:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-nginx-rani'
primary_region = 'nrt'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
